---
name: "tde-remix"
version: "3"
services:

  live-build-amd64:
    image: "tdebuild:amd64"
    platform: linux/amd64
    privileged: true
    build:
      context: .
    container_name: "tdebuild-amd64"
    hostname: "tdebuild-amd64"
    volumes:
      - "${KIWI_SOURCE_DIR:-.}:/live/source:ro"
      - "${KIWI_TARGET_DIR:-.}:/live/target"
    command:
      - >
        kiwi-ng --profile=${KIWI_PROFILE:-Workstation-l10n} --type=iso --debug
        --color-output --shared-cache-dir=/live/target/cache system build
        --description=/live/source/kiwi-descriptions --target-dir=/live/target
    restart: "no"

  live-build-i386:
    image: "tdebuild:i386"
    platform: linux/i386
    privileged: true
    build:
      context: .
      args:
        IMAGE_REGISTRY: "docker.io/i386"
    container_name: "tdebuild-i386"
    hostname: "tdebuild-i386"
    volumes:
      - "${KIWI_SOURCE_DIR:-.}:/live/source:ro"
      - "${KIWI_TARGET_DIR:-.}:/live/target"
    command:
      - >
        linux32 kiwi-ng --profile=${KIWI_PROFILE:-Workstation-l10n} --type=iso --debug
        --color-output --shared-cache-dir=/live/target/cache system build
        --description=/live/source/kiwi-descriptions --target-dir=/live/target
        &&
        echo "Fixing iso image to boot legacy BIOS..."
        &&
        xorriso -indev $$(ls /live/target/TDE-Remix.ix86-*.iso)
        -outdev /live/target/TDE-Remix.i386-bios.iso -publisher TDE_Remix
        -boot_image grub bin_path=boot/ix86/loader/eltorito.img
        -boot_image grub grub2_mbr=/lib/grub/i386-pc/boot_hybrid.img
        -boot_image any grub2_boot_info=on -boot_image any boot_info_table=on
        -boot_image any platform_id=0x00 -boot_image any emul_type=no_emulation
        -joliet on -commit_eject all
    restart: "no"
