#!/usr/bin/bash
#
# Configure the livesys installer

# Add installer setup to liveuser session
echo 'source /usr/local/libexec/livesys/livesys-installer' >> /usr/local/libexec/remix/session-setup

# Remove original installer icon (because it's a duplicate)
rm /usr/share/applications/install-debian.desktop -f
rm /etc/xdg/autostart/calamares-desktop-icon.desktop -f

# Patch squashfs path to match live media
sed -i -e 's/source: ".*"/source: "\/dev\/mapper\/live-base"/' \
-e 's/sourcefs: "squashfs"/sourcefs: "ext4"/' \
/etc/calamares/modules/unpackfs.conf

# Override final apt sources configuration (it's not necessary to modify it, already set)
cp /usr/local/libexec/livesys/sources-final /usr/sbin/sources-final
