#!/usr/bin/bash
#
# live: Init script for live image

## Check if live system is already configured
[ -e /.liveimg-configured ] && exit 0

## Setup liveuser
source /usr/local/libexec/livesys/liveuser-setup

## Setup installer
if [ -f /usr/share/applications/calamares.desktop.orig ]; then
    source /usr/local/libexec/livesys/installer-setup
fi

## Setup desktop
source /usr/local/libexec/livesys/desktop-setup

## Finish liveuser setup
source /usr/local/libexec/livesys/liveuser-finish

#>>>>> Mark things as configured and keep this at the end of this script. <<<<<
: > /.liveimg-configured
