#!/usr/bin/bash
#
# Configure the installer for liveuser

# Query xdg-user-dir directory because different languages
DESKTOP_DIR=$(xdg-user-dir DESKTOP)

## Check if installer is already configured
[ -e $DESKTOP_DIR/livesys-install.desktop ] && exit 0

# Create ~/Desktop just in case this runs before the xdg creation script
mkdir -p $DESKTOP_DIR

# Add installer icon to local applications
cp -a /usr/share/applications/calamares.desktop.orig $DESKTOP_DIR/livesys-install.desktop

# Adjust installer launcher
desktop-file-edit --set-key=Exec --set-value="$(which tdesu) calamares" \
$DESKTOP_DIR/livesys-install.desktop

# Make installer icon executable to disable KDE security warning
chmod +x $DESKTOP_DIR/livesys-install.desktop

# Create liveuser installer application
APPLICATIONS_DIR=$HOME/.local/share/applications
mkdir -p $APPLICATIONS_DIR
ln -s $DESKTOP_DIR/livesys-install.desktop $APPLICATIONS_DIR/livesys-install.desktop
